def print_menu():
    print("*" * 40)
    print("Warehouse control system")
    print("*" * 40)

    print("[1] Register new Item")
    print("[2] List all items")
    print("[3] Update Stock")
    print("[4] List items with no stock")
    print("[5] Remove Item")
    print("[6] Print categories")
    print("[7] Print stock value")
    print("[8] Register purchase")
    print("[9] Register a sale")
    print("[10] List event log")
    print("[x] Exit Application")